{
 "title": "Taxi Duration Model",
 "time": { "from": "2024-03-01T00:00:00.000Z", "to": "2024-03-31T00:00:00.000Z" },
 "panels": [
  {
   "title": "50th Quantile of fare_amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT fare_amount_50th_quantile_metric, \"timestamp\" FROM model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM model_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "description": "Displays the drift of target variable of model over time",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM model_metrics LIMIT 50 "
    }
   ]
  }
 ]
}