version: '3.8'

services:
  mageai:
    image: mageai/mageai
    container_name: mageai_homework
    ports:
      - "6789:6789"
    environment:
      - USER_CODE_PATH=/home/src/notebook
      - PYTHONPATH=/home/src/notebook
    volumes:
      - .:/home/src
    command: /app/run_app.sh mage start notebook
    networks:
        - app-network
  
  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/mlflow_data:/home/mlflow_data/"
    command: mlflow server --backend-store-uri sqlite:///home/mlflow_data/mlflow.db --host 0.0.0.0 --port 5000
    networks:
      - app-network

networks:
  app-network:
    name: app-network