version: '3.7'

# volumes:
#   grafrana_data: {}

networks:
  front-tier:
  back-tier:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - back-tier
  
  adminers:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db
  
  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./dashboards:/opt/grafana/dashboards:ro
    networks:
      - back-tier
      - front-tier
    restart: always
    depends_on:
      - db
