version: '3.8'

services:
  localstack-s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    networks:
      - integration-batch-networks

networks:
  integration-batch-networks:
    name: integration-batch-networks
    external: false